### ISSUE TITLE
Cookbook missing from the supermarket

### ISSUE THREAD

**Issue by gravesb** [cerner/ops_tcpdump_handler#3]
I followed the instructions in the README and added `cookbook 'ops_tcpdump_handler'` to my Berksfile but when I ran berks install I got a failure that it was unable to find a solution.  I then looked for the cookbook in the supermarket and realized it wasn't present.  You should either release it to the supermarket or fix the README to reference the git location so the usage steps actually work.

**Comment by david-crowder** [comment]
Tagged and uploaded to the public supermarket https://supermarket.chef.io/cookbooks/ops_tcpdump_handler
